# Generated by Django 5.2.6 on 2025-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_authors_alter_book_isbn_alter_book_isbn13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='Sin género', max_length=100),
        ),
    ]
