# Generated by Django 5.2.5 on 2025-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
