# Generated by Django 5.2.5 on 2025-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='best_book_id',
            new_name='num_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books_count',
            new_name='text_reviews_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='original_publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_4',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_5',
        ),
        migrations.RemoveField(
            model_name='book',
            name='small_image_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_ratings_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_text_reviews_count',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
