# Generated by Django 5.2.5 on 2025-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_best_book_id_book_num_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
