# Generated by Django 5.2.4 on 2025-10-17 21:27

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_alter_book_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="emb",
            field=models.BinaryField(default=books.models.get_default_array),
        ),
    ]
