# Generated by Django 5.2.4 on 2025-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_book_emb"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
