# Generated by Django 5.2.4 on 2025-10-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_book_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="emb",
        ),
    ]
