# Generated by Django 5.2.4 on 2025-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_remove_book_cover_remove_book_emb"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="emb",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
