# Generated by Django 5.2.4 on 2025-10-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_book_emb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="emb",
            new_name="embeddings",
        ),
    ]
