# Generated by Django 5.2.4 on 2025-10-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_remove_book_book_id_remove_book_isbn13_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
